.github/ISSUE_TEMPLATE/01-bug-report.yml, .github/ISSUE_TEMPLATE/02-feature-request.yml, .github/PULL_REQUEST_TEMPLATE.md
Pretty much just pulled the ones from the website repo and modified them where needed
Note: we don't have COLLABORATORS.md yet but I still kept the link there for when we do. Excluded any npm commands until we know what they'll be for tests, etc.
Partially takes care of #13
=> meta: add issue and pr templates

src/generators.mjs, src/generators/index.mjs, src/generators/json-simple/index.mjs, src/generators/legacy-html/assets/.gitkeep, src/generators/legacy-html/index.mjs, src/generators/types.d.ts, src/metadata.mjs, src/parser.mjs, src/types.d.ts
This PR introduces the base generator modules. This should be integrated together with the CLI Pull Request, as the CLI should pass the CLI options to the generators.
Please verify that the code works and that it is well documented.
```tsx
import { resolve } from 'node:path';
import createGenerator from './src/generators.mjs';
import createLoader from './src/loader.mjs';
import createParser from './src/parser.mjs';
const { loadFiles } = createLoader();
const { parseApiDocs } = createParser();
const apiDocFiles = loadFiles('../node/doc/api/http.md');
const parsedApiDocs = await parseApiDocs(apiDocFiles);
const { runGenerators } = createGenerator(parsedApiDocs);
await runGenerators({
generators: ['jsonSimple'],
output: resolve('.'),
});
```
Notes: I assume the CLI script will pass the …
=> feat: introduce based generator logic

bin/.gitkeep, bin/cli.mjs, package-lock.json, package.json, src/constants.mjs, src/generators/index.mjs, src/generators/json-simple/index.mjs, src/generators/legacy-html/index.mjs
With this PR, we have added parsing features via CLI.
The following commands you can use:
`-i`, `--input` `<patterns...>`    Specify input file patterns using glob syntax
`-e`, `--exclude` `<patterns...>`  Specify patterns to exclude files from being processed
`-o`, `--output` `<path>`          Specify the output directory path
`-t`, `--target` `<mode>`          Set the processing mode (default: "mdx")
`-h`, `--help`                   display help for command
Just an idea; In the future, we may add verbose to debug logs or silent mode to hide logs 🤔 
- I left a todo in `cli.mjs` because I wasn't sure where and how to connect to Parser. I think after [#33](https://github.com/nodejs/api-docs-tooling/pull/33) is closed, we can determine how we will use it here and organize it
- I used …
=> feat: introduced CLI mode to the parser

bin/cli.mjs, eslint.config.mjs, package-lock.json, package.json, src/constants.mjs, src/generators.mjs, src/generators/json-simple/index.mjs, src/generators/types.d.ts, src/releases.mjs, src/types.d.ts
This PR introduces the ability for the API docs tooling to retrieve the current running/target Node.js version and all major versions from the CHANGELOG.md file; this is important since relative version metadata is necessary during the doc build process.
In the future, when the proper React/MDX generators are created, this information will be used for the Navigation of different Node.js versions and + for knowing what version the API docs are targeting.
This will also be used for the legacy API doc tooling.
=> feat: introduce release metadata to generators

eslint.config.mjs, src/constants.mjs, src/generators.mjs, src/generators/json-simple/index.mjs, src/generators/types.d.ts, src/loader.mjs, src/metadata.mjs, src/parser.mjs, src/queries.mjs, src/releases.mjs, src/types.d.ts, src/utils/generators.mjs, src/utils/parser.mjs, src/utils/remark.mjs
This PR incorporates the code refactors and bug fixes introduced from #55 into the codebase, splitting the actual generator changes done in #55 from the plain bug fixes and code refactors.
- Move remark imports and remark logic (for crating processors) to a dedicated `remark.mjs` file
- Updated ESLint config to be "namespace"
- Export the common types into a global namespace, to prevent unnecessary repeated JSdoc type imports and typedefs
- Updated some imports to by type imports whenever possible
- Reordered imports using default import sorter
- Support multiple stability index entries per section, instead of just one.
- Merge metadata `update` entries into `changes` by mapping the `update` entries into the same format used by `changes` within `metadata.mjs`
- Better types for WithJSON …
=> refactor: applied bug fixes and code refactor from #55

bin/cli.mjs
With this PR, if the input pattern points to more than one file, we expect it to work for all of them. In the current version, it only produces output for the first file.
For example, expect the command below to produce output for all markdown files in the `api` directory;
```sh
npx api-docs-tooling -i PATH_TO_NODE/doc/api/*.md -t json-simple -o .
```
=> fix: cli multiple input

README.md
While starting work on a different aspect of this codebase, I sorta forgot how to use it :smile: This PR adds a very simple usage section to the README that is a moment in time snapshot of the help output.
Will this output drift over time? It could. My team maintains [markdown-inject](https://www.npmjs.com/package/markdown-inject) for use cases like this, but it doesn't need to be introduced.
=> docs: add README help/usage output

src/constants.mjs
:sweat_smile: how did I not notice this?
---
Quick fix of a mistake I made when moving the constants to the seperate file.
=> chore: fix typo in `environment-variables-1` slug

src/generators/man-page/utils/converter.mjs, src/test/man-page.test.mjs
Some flags (rarely, but still) have optional parameters, which was not reflected in the generated man-page.
See the tests to ensure validation.
=> fix(man-page): account for optional flag arguments

package.json, src/index.mjs
This PR adds the ability to execute this from another JS file, without the use of the CLI. That way, `man-page`, and any future generators wouldn't be limited to the CLI for execution
Verify that all execution is working as planned.
- [-] I've covered new added functionality with unit tests if necessary.
=> feat: allow non-cli execution

src/test/queries.test.mjs, src/utils/parser.mjs, src/utils/tests/parser.test.mjs
According to the legacy parser:
<https://github.com/nodejs/node/blob/0a00217a5f67ef4a22384cfc80eb6dd9a917fdc1/tools/doc/json.mjs#L478-L489>
As shown above, the heading should *not* have a default value. The generators should decide whether a `misc` or `module` heading is appropiate based on the heading of the parent.
See updated tests
#139
=> fix: don't assume heading type is `module`

src/generators/man-page/index.mjs
:sweat_smile: This branch should've created on my fork, not this repo. Regardless, this is a chore for post #137 to allow the `man-page` to be generated programmatically.
=> chore: allow `man-page` from non-CLI

eslint.config.mjs, package-lock.json, package.json, src/generators/json-simple/index.mjs, src/generators/legacy-html-all/index.mjs, src/generators/legacy-html/index.mjs, src/generators/man-page/index.mjs, src/generators/man-page/utils/converter.mjs, src/loader.mjs, src/metadata.mjs, src/queries.mjs, src/utils/remark.mjs, src/utils/unist.mjs
I thought the Eslint JSDoc rules would make sense for comments that we might miss or were not properly formatted. I've updated the missing or incorrectly indented sections with this PR
=> meta: Eslint JSDoc plugin

README.md, shiki.config.mjs, src/constants.mjs, src/generators/index.mjs, src/generators/legacy-html/assets/api.js, src/generators/legacy-json-all/index.mjs, src/generators/legacy-json-all/types.d.ts, src/generators/legacy-json/constants.mjs, src/generators/legacy-json/index.mjs, src/generators/legacy-json/types.d.ts, src/generators/legacy-json/utils/buildHierarchy.mjs, src/generators/legacy-json/utils/buildSection.mjs, src/generators/legacy-json/utils/parseList.mjs, src/generators/legacy-json/utils/parseSignature.mjs, src/metadata.mjs, src/parser.mjs, src/queries.mjs, src/test/metadata.test.mjs, src/test/queries.test.mjs, src/types.d.ts, src/utils/parser.mjs
Closes #57
Closes #141 
Closes #92
---
This is an extension of #92. This is a seperate PR due to a rebase that caused merge conflicts. 
See https://github.com/nodejs/api-docs-tooling/pull/92 for a description
```bash
FILENAME="$1"
NODE="path/to/node/repo"
API_DOCS_TOOLING="path/to/api-docs/tooling/repo"
DOC="$NODE/doc/api/$FILENAME.md"
OUTPUT_DIR="output"
NEW_DIR="$OUTPUT_DIR/new"
OLD_DIR="$OUTPUT_DIR/old"
SORT_JSON=$(cat <<EOF
def sorted_walk(f):
. as \$in
| if type == "object" then
reduce keys[] as \$key
( {}; . + { (\$key):  (\$in[\$key] | sorted_walk(f)) } ) | f
elif type == "array" then map( sorted_walk(f) ) | f
else f
end;
def normalize: sorted_walk(if type == "array" then sort else . end);
normalize
EOF
)
initialize_output() {
rm -rf "$OUTPUT_DIR" && mkdir -p "$NEW_DIR" "$OLD_DIR" …
```
=> feat: legacy json generator

package-lock.json, package.json, src/generators/legacy-html/utils/buildContent.mjs, src/generators/legacy-json/types.d.ts, src/generators/legacy-json/utils/parseList.mjs, src/generators/man-page/utils/converter.mjs, src/queries.mjs, src/types.d.ts
This PR is a "hot-fix" from the deprecation warning, by using @types/mdast instead of "mdast" which now simply is the "remark" package.
=> chore: use @types/mdast

README.md, src/generators/addon-verify/constants.mjs, src/generators/addon-verify/index.mjs, src/generators/addon-verify/utils/updateFilesForBuild.mjs, src/generators/index.mjs
Create addon-verify generator
I compared the output of the [old generator](https://raw.githubusercontent.com/nodejs/node/refs/heads/main/tools/doc/addon-verify.mjs) with this one, and they are identical.
Fixes #151
=> feat: introduce addon-verify generator

.gitignore, src/generators/legacy-html-all/index.mjs, src/generators/legacy-html/index.mjs, src/generators/legacy-html/utils/buildDropdowns.mjs, src/generators/types.d.ts
This PR does a bunch of hotfixes:
- Fix generation that was not considering REPLACEME
- Fix declare global for some types
- Updated Gitignore
- Also Minify CSS
Closes https://github.com/nodejs/api-docs-tooling/issues/176
=> hotfix: type and build fixes

src/generators/legacy-html/assets/api.js, src/generators/legacy-html/assets/style.css, src/generators/legacy-html/template.html, src/generators/legacy-html/utils/buildDropdowns.mjs
This PR ports changes from https://github.com/nodejs/node/pull/56749 and https://github.com/nodejs/node/pull/56755#pullrequestreview-2574320497 and https://github.com/nodejs/node/pull/56750
cc @aduh95
=> chore: port changes from node core

README.md, bin/cli.mjs, src/loaders/markdown.mjs
Allows for files to be ignored (aka removed) from the input so they won't be passed onto the generators. This is needed to support the `skip_apidoc_files` in Node's makefile (https://github.com/nodejs/node/blob/823c9b70c727e2efaa6dfd8e97551c31b45ff666/Makefile#L783)
=> feat: --ignore flag

.github/dependabot.yml, README.md, package-lock.json, package.json, src/generators.mjs, src/generators/index.mjs, src/generators/orama-db/index.mjs, src/generators/orama-db/types.d.ts
This pull request introduces a new generator for creating an Orama database for the API documentation. The changes include adding new dependencies, importing and integrating the new generator, and implementing the generator logic.
close #65 
> [!NOTE]
>  The output of `v22.11.0` is 3Ko
=> feat(generator/orama-db): introduce

src/linter/tests/reporters/console.test.mjs, src/linter/tests/reporters/github.test.mjs
On many windows machines, lines end with `\r\n`, rather than just `\n`. This PR updates the tests to trim off the newlines, so that the test passes on both Windows and Posix machines.
=> fix(test): work on both CRLF and LF machines

package-lock.json, package.json, src/loaders/markdown.mjs
On Windows, using a backslash in the path (e.g., `-i .\docs\buffer.md` rather than `-i ./docs/buffer.md`) prevents the glob from matching correctly and triggers an internal assertion. This issue is resolved by using the `fs` version of `globSync`.
=> fix: use `globSync` from `fs`

src/loaders/javascript.mjs, src/loaders/markdown.mjs
I missed the `javascript.mjs` file. (And while I'm following up, I should've used the `node:` prefix)
=> fix: followup globSync fix

bin/cli.mjs
On some Windows machines (like my own), calling `process.exit()` will exit the program before all internal assertions can be completed, leading to a failed libuv assertion.
P.S. I may have hit peak programmer status—I committed, tested, and opened a PR for this change all from my phone 🤣
=> fix: don’t force exit the program

package-lock.json, package.json, src/loaders/javascript.mjs, src/loaders/markdown.mjs
=> revert: undo globSync from fs

src/linter/rules/invalid-change-version.mjs, src/linter/tests/fixtures/entries.mjs, src/linter/tests/fixtures/invalidChangeVersion-environment.mjs, src/linter/tests/rules/invalid-change-version.test.mjs
Per https://github.com/nodejs/node/pull/57343#pullrequestreview-2711832418
> * We should not report REPLACEME as an invalid version.
> * We should report invalid versions as a hard failure.
=> chore(lint): report error on invalid change versions, except REPLACEME

src/linter/rules/invalid-change-version.mjs, src/linter/tests/fixtures/invalidChangeVersion-environment.mjs
Ref: https://github.com/nodejs/node/pull/57343#issuecomment-2781707538
=> fix(lint): hardcode ignored invalid change versions

bin/cli.mjs, src/generators.mjs, src/generators/index.mjs, src/generators/json-simple/index.mjs, src/generators/legacy-html-all/index.mjs, src/generators/legacy-html/index.mjs, src/generators/legacy-html/utils/buildDropdowns.mjs, src/generators/legacy-json/utils/buildSection.mjs, src/generators/types.d.ts, src/linter/tests/fixtures/entries.mjs, src/metadata.mjs, src/test/metadata.test.mjs, src/threading.mjs, src/threading/index.mjs, src/threading/worker.mjs, src/types.d.ts
This PR offloads generators to worker threads. I've done a check of each generator, and nothing crashes, however, please please do a run through to verify nothing changed.
Because some functions cannot be cloned, `toString()` (on SemVer) has been replaced with `.version`, and similar for other SemVer related activities.
The output should be identical to the current generation.
See https://openjs-foundation.slack.com/archives/CVAMEJ4UV/p1744161814523689
=> feat(perf): offload generators to worker threads

src/generators/legacy-html/utils/buildContent.mjs
Also removes the `b` wrappers, as IMO it makes little sense to put an emphasis on those.
=> fix: make casing consistent

src/releases.mjs
We should only get the file from the file system when we're certain the URL is referencing a file. This prevents misinterpreting other protocols—like `http` instead of `https`—as file paths.
See description
=> fix(changelog): allow for non-https protocols

README.md, bin/cli.mjs, bin/commands/generate.mjs, bin/commands/index.mjs, bin/commands/interactive.mjs, bin/commands/lint.mjs, bin/commands/list.mjs, bin/utils.mjs, eslint.config.mjs, package-lock.json, package.json, src/generators/legacy-html/utils/buildContent.mjs
This PR splits the CLI into subcommands, following the structure shown below:
```
api-docs-tooling
│
├── generate       → Generate API docs
├── lint           → Run linter independently
├── list
│   ├── generators → List available generators
│   ├── rules      → List available linter rules
│   └── reporters  → List available reporters
├── interactive    → Launch a guided CLI wizard
```
Every command shown in the updated README should work as intended.
Fixes #148
=> feat(cli): split cli into sub commands

.github/PULL_REQUEST_TEMPLATE.md, .lintstagedrc.json, CONTRiBUTING.md
`CONTRIBUTING.md` is referenced on pr template but it's ins't on the repo. So create one + update pr template.
No related issues
- **NA** I've covered new added functionality with unit tests if necessary.
=> chore(dx): contributing.md + pr template

src/utils/parser/constants.mjs
Mirrors changes in nodejs/node#58294
=> fix: CryptoKey.algorithm type and other interfaces

src/linter/reporters/console.mjs, src/linter/tests/reporters/console.test.mjs
If all of these are sent to `stdout` and the user pipes the output using `>`, the lint errors will be included. Instead, the outputs should be directed appropriately based on the context, right?
=> chore(lint): use `console[xyz]` over `process`

src/generators/orama-db/index.mjs
Ref https://openjs-foundation.slack.com/archives/CVAMEJ4UV/p1748537244707229?thread_ts=1748470939.551939&cid=CVAMEJ4UV
=> fix(orama): fix various bugs in Orama-DB generator

src/releases.mjs
Re https://github.com/nodejs/node/pull/57343#issuecomment-2917116402
=> fix: allow for relative paths for changelog file

src/types.d.ts
=> fix(`HeadingMetadataEntry`): add `global`

src/generators/jsx-ast/index.mjs
=> fix(jsx-ast): use metadata generator

CONTRIBUTING.md
Let's give new users as much information as we can in order to set them up for success.
=> chore(docs): update `CONTRIBUTING.md` with additional information

src/linter/constants.mjs, src/linter/rules/__tests__/invalid-change-version.test.mjs, src/linter/rules/invalid-change-version.mjs, src/linter/types.d.ts, src/linter/utils/__tests__/yaml.mjs, src/linter/utils/yaml.mjs, src/utils/parser/index.mjs
Improve `invalid-change-version` to provide users with more precise issue locations instead of only the entire YAML node position.
```
npx api-docs-tooling lint -i doc/api/*.md
```
=> feat: improve changes issues positions

bin/commands/__tests__/index.test.mjs, codecov.yml, src/generators/__tests__/index.test.mjs
Follow-up #315: Prevents that from happening in the future by validating the command objects as a test.
=> feat(test): validate commands and generators

src/utils/highlighter.mjs
Using the WASM generator rather than the JS one results in ~50% cheaper runs.
=> feat(shiki): use wasm engine

src/generators/legacy-json/utils/__tests__/parseList.test.mjs, src/generators/legacy-json/utils/parseList.mjs
Fixes #321 by verifying the list meets the following structure before parsing it as a list of options:
1. Must start with a `code`
2. Followed by a space
3. Followed by a link whose first character is `<`
=> fix(legacy-json): verify list type

codecov.yml
Although we haven’t reached 80% coverage yet, our patch coverage threshold has successfully served its purpose by encouraging meaningful test coverage in our PRs. Now that we’re above 70%, I’m confident we can continue to improve coverage even without enforcing the threshold.
=> chore(cov): disable patch coverage

src/utils/parser/constants.mjs
Ref: https://github.com/nodejs/node/pull/58930
CC @ovflowd
=> chore(types): mirror https://github.com/nodejs/node/pull/58930

src/generators/legacy-json/utils/__tests__/parseSignature.test.mjs, src/generators/legacy-json/utils/parseSignature.mjs
Previously, the signature parsing would parse trailing brackets as if they affect the _current_ parameter, rather than the _next_ parameter.
Because of this, `mand[, opt]` would be seen as an optional param named "mand", and a mandatory parameter "opt". Now, trailing brackets correctly apply to the _next_ parameter.
=> fix(legacy-json): more robust signature parsing

src/generators/metadata/utils/parse.mjs, src/utils/parser/constants.mjs, src/utils/parser/index.mjs, src/utils/queries/index.mjs
Fixes #346 by adding a transformer for Unix Manual syntax. That way, when `chmod(1)` (or similar) is put the documentation, it'll link to the https://man7.org/linux/man-pages/ reference.
=> fix(parser): transform man pages

.github/workflows/generate.yml
(CC @ovflowd)
Let's see if this speeds up the workflows significantly. If not, we can use a shared step, but this may be enough.
=> chore(ci): sparse-checkout

package-lock.json, package.json, src/generators/web/template.html, src/generators/web/utils/processing.mjs
Remove the mustache dep. I can't understand why replacing the script didn't work, the template gets rendered multiple times. but concatenation works 🤔
```
npx doc-kit generate -i doc/api/*.md -t web -o out/
```
=> refactor: remove mustache

src/generators/web/constants.mjs, src/generators/web/utils/bundle.mjs, src/generators/web/utils/generate.mjs, src/generators/web/utils/processing.mjs
Currently, `doc-kit` does not work on Windows due to a Rolldown issue, and a paths issue.
This PR fixes the paths issue by using Windows-safe paths.
Additionally,
- When not minified, there is a chance that the code will end with an `//#endregion` comment. We need to add a newline before the `return`
- We set the variable `code =` to to dehydration, not our generated variable. TBH, I'm not sure how this worked at all previously...
@TheAlexLichter There appears to be a bug when building this on Windows:
It appears to import everything twice. Once using a Unix path, and once using a Windows path.
=> fix(win): use windows-safe paths

src/generators/jsx-ast/constants.mjs, src/generators/jsx-ast/utils/buildContent.mjs, src/generators/web/ui/index.css
Improves the deprecation page by:
1. Not slicing the `DEPXXX:` off the title
2. Not bolding the code blocks, they should inherit their weight
3. Putting the deprecation type inside an AlertBox
=> feat(web): improve deprecation page

.c8rc.json
Remove `.d.ts` files from coverage
```sh
npm run test:coverage
```
=> chore: ignore types files on coverage

src/utils/parser/constants.mjs
Broken out of: #366
Fixes: #356
This PR moves the common patterns used by `DOC_API_HEADING_TYPES` into there own RegExps, to prevent de-syncing between the RegExps.
=> fix(regexp): re-use common patterns

.github/dependabot.yml, .github/workflows/update-internal-dependencies.yml
This PR improves our Dependabot groups, and adds support for updating `@node-core/*` packages, since Dependabot can't. (Because those packages don't currently follow semver)
=> feat(deps): update dependabot config and add support for @node-core

CONTRIBUTING.md
Replaces old api-docs-tooling with doc-kit
=> Update CONTRIBUTING.md for new repo name

.github/dependabot.yml, package-lock.json, package.json, src/utils/parser/__tests__/index.test.mjs, src/utils/parser/constants.mjs, src/utils/parser/index.mjs
The `globals` library is updated with every builtin global every month (https://github.com/sindresorhus/globals/blob/main/.github/workflows/update.yml), so we can safely rely on it to populate our builtin globals.
IMO this is a safer alternative than having us manually update this list.
Ref #319
=> fix(globals): use `globals` for globals

.github/workflows/generate.yml
Fixes https://github.com/nodejs/doc-kit/issues/396
=> chore(ci): add `web` to generation matrix

src/utils/parser/constants.mjs
These are missing from our list of globals (I didn't realize `globals.builtin` didn't include them in 0ecb11e818083a87d3eee8df519650760fb0dfe4)
=> fix(globals): add `ErrorEvent` and `TypedArray`

bin/commands/interactive.mjs, bin/utils.mjs
Requesting fast-track, as this is a bug fix.
=> fix(logger): use default export

package-lock.json, package.json
`@actions/core` is used in the GitHub logger transport despite not actually being installed directly, meaning it's only available when `@reporters/github` is downloaded w/ dev dependencies. In Node core we don't install dev dependencies causing this to throw.
=> fix: add `@actions/core` as dependency

src/utils/parser/constants.mjs
Fixes: #378
Companion: https://github.com/nodejs/node/pull/60087
Makes the RegExp's more strict by removing all optional pieces.
=> feat(regexp): stricter regexps
